version: 2
jobs:
  build:
    working_directory: ~/cn-app
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
        name: Run tests
        command: yarn test
  
  lint:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
        name: Run eslint
        command: yarn lint

  deploy:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
        name: Deploy
        command: echo 'deploy script comes here'

workflows:
  version: 2
  flow:
    jobs:
      - build
      - test:
        requires:
            - build
      - lint:
        requires:
            - build
      - deploy:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master